POST http://localhost:8080/events
content-Type: application/json

{
    "name": "second event", 
    "description": "second event description", 
    "location": "toronto", 
    "date_time": "2025-01-02T15:30:00.000Z"
}