DELETE http://localhost:8080/events/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wbGUyQGdtYWlsLmNvbSIsImV4cCI6MTczMTkzOTMwNCwidXNlcklkIjoyfQ.mKJsHaBOCm-WkMjl8yy2-DdsS6GAG9PZywgfkmK14pQ