PUT http://localhost:8080/events/11
Content-Type: application/json

{
    "name": "firsttt event", 
    "description": "firstttt event description", 
    "location": "japan", 
    "date_time": "2025-01-04T15:30:00.000Z"
}